package network.protocol;

public enum CollectionParameter {
    GO_COLLECTION,
    START_COLLECTION,
    NEW_DECK,
    NEW_DECK_SUCCESS,
    CARD_TO_DECK,
    CARD_FROM_DECK,
    SELECT_DECK_GAME,
    DELETE_DECK,
    EDIT_DECK,
    EDIT_DECK_UNSUCCESSFUL,
    TRANSFER_CARD_DECK_SUCCESS,
    EDIT_DECK_SUCCESS,
    DELETE_DECK_SUCCESS,
    SELECT_DECK_GAME_SUCCESS
}
